spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/autoconfiguration
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          facebook:
            client-id:
            client-secret:
custom:
  oauth2:
    kakao:
      client-id: